apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <BASE64_ENCODED_CA_CERT>
    server: https://127.0.0.1:6443
  name: demo-cluster
contexts:
- context:
    cluster: demo-cluster
    user: demo-admin
  name: demo-admin@demo-cluster
current-context: demo-admin@demo-cluster
kind: Config
preferences: {}
users:
- name: demo-admin
  user:
    client-certificate-data: <BASE64_ENCODED_CLIENT_CERT>
    client-key-data: <BASE64_ENCODED_CLIENT_KEY>
