apiVersion: v1
kind: Secret
metadata:
  name: cloud-secrets
  namespace: thecloud
type: Opaque
stringData:
  # Using default credentials for local dev/test
  DATABASE_URL: "postgres://cloud:cloud@pgbouncer-service:5432/thecloud?sslmode=disable"
  REDIS_URL: "redis-service:6379" # Will be updated to cluster later
  SECRETS_ENCRYPTION_KEY: "8b93d18075ca022a96551ea481cf207027c63f3603ff0865757784bc19d07375"
